# Generated by Django 3.2.7 on 2024-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='employee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
