# Generated by Django 3.2.7 on 2024-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gdci',
            field=models.BooleanField(default=False),
        ),
    ]
