# Generated by Django 3.2.7 on 2024-08-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0008_auto_20220804_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderacknowledgement',
            name='gdci_invoice_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='gdci_project_manger',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='gdci_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
